### ISSUE TITLE
Format for ENV

### ISSUE THREAD

**Issue by mrbrimm** [straightupjac/nft-merkle-whitelist-scaffold#2]
I keep getting errors saying the private key isn't 32 bytes. If I place in config directly after 0x it will compile. 

Another issue is after that I run the deploy script is it says invalid endpoint. could you share an example ENV file populated please?

Thanks!

**Comment by straightupjac** [comment]
hey! the private key should be exactly what a wallet like metamask gives you as private key - do you have a burner account in which you feel comfortable sharing your env variable so I can take a look?

**Comment by mrbrimm** [comment]
Thanks! I figured it out. Was an issue with my ENV file setup.
